# Generated by Django 4.1.3 on 2023-04-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6)),
                ('address', models.CharField(max_length=250)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB+'), ('AB-', 'AB-')], max_length=6)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC')], max_length=11)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('medical_history', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
                ('profile_picture', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'permissions': [('view_history', 'Can view history')],
            },
        ),
        migrations.CreateModel(
            name='MedicalPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6)),
                ('hospital_staff_id', models.CharField(max_length=25)),
                ('profile_picture', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
                ('specialty', models.CharField(choices=[('epidemiologist', 'Epidemiologist'), ('general practitioner', 'General practitioner'), ('pediatrician', 'Pediatrician'), ('dentist', 'Dentist'), ('surgeon', 'Surgeon'), ('dermatologist', 'Dermatologist'), ('plastic surgeon', ' Plastic Surgeon'), ('psychiatrist', 'Psychiatrist')], max_length=20)),
                ('professional_license', models.CharField(max_length=25, unique=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.hospitalmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'profile_picture'],
                'permissions': [('view_history', 'Can view history')],
            },
        ),
    ]
