# Generated by Django 4.1.7 on 2023-03-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='clinical_profession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hospital.hospitalstaff'),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalmodel'),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hospital.staffdepartment'),
        ),
    ]
