# Generated by Django 4.1.7 on 2023-03-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='patient_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='medical_history',
            field=models.ImageField(default='blank_profile_pic.png', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='profile_picture',
            field=models.ImageField(default='blank_profile_pic.png', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
