# Generated by Django 4.1.3 on 2023-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmodel',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
