# Generated by Django 4.1.7 on 2023-04-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_hospitalmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_personnel', to='profile.hospitalmodel'),
        ),
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='specialty',
            field=models.CharField(choices=[('epidemiologist', 'Epidemiologist'), ('general practitioner', 'General practitioner'), ('pediatrician', 'Pediatrician'), ('dentist', 'Dentist'), ('surgeon', 'Surgeon'), ('dermatologist', 'Dermatologist'), ('plastic surgeon', ' Plastic Surgeon'), ('psychiatrist', 'Psychiatrist')], default='epidemiologist', max_length=20),
        ),
    ]
