# Generated by Django 4.1.7 on 2023-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_rename_patient_phone_patientmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmodel',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
