# Generated by Django 4.1.7 on 2023-03-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_medicalpersonnel_clinical_profession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpersonnel',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='clinical_profession',
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='speciality',
        ),
    ]
