# Generated by Django 4.1.7 on 2023-03-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_patientmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB+'), ('AB-', 'AB-')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6),
        ),
    ]
