# Generated by Django 4.1.7 on 2023-03-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('profile', '0003_alter_medicalpersonnel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpersonnel',
            options={'ordering': ['hospital__name', 'hospital__address', 'user__first_name', 'user__last_name', 'clinical_profession__staffs', 'profile_picture'], 'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='clinical_profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='hospital.hospitalstaff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hopsital_name', to='hospital.hospitalmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hospital.staffdepartment'),
            preserve_default=False,
        ),
    ]
