# Generated by Django 4.1.7 on 2023-03-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_medicalpersonnel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpersonnel',
            options={'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='clinical_profession',
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicalpersonnel',
            name='speciality',
        ),
    ]
