# Generated by Django 4.1.7 on 2023-03-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('profile', '0005_alter_medicalpersonnel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalpersonnel',
            options={'ordering': ['hospital__name', 'hospital__address', 'user__first_name', 'user__last_name', 'profile_picture'], 'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hopsital_name', to='hospital.hospitalmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='medical_profession',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalpersonnel',
            name='specialty',
            field=models.CharField(choices=[('epidemiologist', 'Epidemiologist'), ('general practitioner', 'General practitioner'), ('pediatrician', 'Pediatrician'), ('dentist', 'Dentist'), ('surgeon', 'Surgeon'), ('dermatologist', 'Dermatologist'), ('plastic surgeon', ' Plastic Surgeon'), ('psychiatrist', 'Psychiatrist')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
