# Generated by Django 4.1.7 on 2023-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
