# Generated by Django 4.1.7 on 2023-03-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_service', '0003_alter_doctor_options_alter_doctor_first_name_and_more'),
        ('appointment_service', '0002_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to='doctor_service.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.DateTimeField(verbose_name='%d/%m/%Y %H:%M'),
        ),
    ]
