# Generated by Django 4.1.7 on 2023-04-02 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('profile', '0001_initial'),
        ('appointment_service', '0003_appointmentmodel_appointmentpagemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCartModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('cancled', 'CANCLED'), ('approved', 'APPROVED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentpagemodel',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_detail', to='hospital.hospitalmodel'),
        ),
        migrations.CreateModel(
            name='AppointmentCartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('booking_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointment_service.appointmentcartmodel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.medicalpersonnel')),
            ],
            options={
                'unique_together': {('booking_cart', 'hospital')},
            },
        ),
    ]
