# Generated by Django 4.1.7 on 2023-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_service', '0003_alter_appointment_doctor_alter_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
