# Generated by Django 4.1.3 on 2023-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_day', models.DateField()),
                ('booked_status', models.CharField(choices=[('pending', 'PENDING'), ('cancled', 'CANCLED'), ('approved', 'APPROVED')], default='pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('cancel_appointment', 'Can cancel appointment')],
            },
        ),
    ]
