# Generated by Django 4.1.7 on 2023-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'permissions': [('cancel_appointment', 'Can cancel appointment')]},
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booked_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('approved', 'APPROVED')], default='pending', max_length=9),
        ),
    ]
