# Generated by Django 4.1.7 on 2023-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.AddField(
            model_name='register',
            name='is_verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
