# Generated by Django 4.1.7 on 2023-03-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalmodel',
            old_name='doctor_lastname',
            new_name='doctor_last_name',
        ),
    ]
