# Generated by Django 4.1.7 on 2023-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_doctor_lastname_hospitalmodel_doctor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='doctors_specialty',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_name',
            field=models.CharField(max_length=250),
        ),
    ]
