# Generated by Django 4.1.7 on 2023-03-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('gender',)},
        ),
    ]
