# Generated by Django 4.1.7 on 2023-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=16)),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('surgery', 'Surgery'), ('dermatology', 'Dermatology'), ('anesthesiology', 'Anesthesiology'), ('ophthalmology', 'Ophthalmology'), ('clinical immunology', 'Clinical Immunology'), ('allergy', 'Allergy'), ('clinical pathology', 'Clinical Pathology')], max_length=20)),
                ('available_days', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
