# Generated by Django 4.1.7 on 2023-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_service', '0002_alter_doctor_available_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('available_days',)},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('epidemiologist', 'Epidemiologist'), ('general practitioner', 'General practitioner'), ('pediatrician', 'Pediatrician'), ('dentist', 'Dentist'), ('surgeon', 'Surgeon'), ('dermatologist', 'Dermatologist'), ('plastic surgeon', ' Plastic Surgeon'), ('psychiatrist', 'Psychiatrist')], default='psychiatrist', max_length=20),
        ),
    ]
